---
extends: [
   vizzuality
]
globals:
  require: true
  config: true
  __DEV__: true
parser: babel-eslint
parserOptions:
  ecmaVersion: 7
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
  sourceType: module
plugins: [react, prettier]
rules:
  jsx-a11y/click-events-have-key-events: 'warn'
  jsx-a11y/no-noninteractive-element-interactions: 'warn'
  import/extensions: [error, {"js": never, "jsx": never}]

settings:
  import/resolver: webpack
