---
extends: [
   vizzuality
]
globals:
  require: true
  config: true
  window: true
  __DEV__: true
parser: babel-eslint
parserOptions:
  ecmaVersion: 7
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
  sourceType: module
plugins: [react, prettier]
rules:
  jsx-a11y/click-events-have-key-events: 'warn'
  jsx-a11y/no-noninteractive-element-interactions: 'warn'
  jsx-a11y/no-static-element-interactions: 'warn'
  import/extensions: [error, {"js": never, "jsx": never, "packages": always}]
  react/jsx-one-expression-per-line: 'warn'
  react/sort-comp: 0
  import/prefer-default-export: 0
  class-methods-use-this: 1
  react/destructuring-assignment: 1
  import/no-extraneous-dependencies: 0

settings:
  import/resolver: webpack
